<a href="https://colab.research.google.com/github/MatthewRomanishin/courses/blob/main/matmech/mathmech_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **Жорданова форма**







Дан массив из 3-х действительных собственных чисел $$\lambda_i \in \mathbb{R}$$
​	
и их алгебраическими кратностями $$n_i \in \mathbb{N}$$
Необходимо построить Жорданову матрицу по этим собственным числам.

Пример:
$$
\begin{pmatrix}
2.2 & 1 & 0 & 0 & 0 & 0 \\
0 & 2.2 & 0 & 0 & 0 & 0 \\
0 & 0 & 3 & 1 & 0 & 0 \\
0 & 0 & 0 & 3 & 1 & 0 \\
0 & 0 & 0 & 0 & 3 & 0 \\
0 & 0 & 0 & 0 & 0 & 5
\end{pmatrix}$$


Напоминание, Жорданова матрица состоит из блоков, где на главной диагонали стоят собственные числа, а следующая диагональ блока заполнена единицами.

Блоки идут **в том же порядке**, что и в листе на входе. (Хотя в реальной Жордановой матрице блоки могут идти в любом порядке)

###Sample
####Input:
```pyhton
X = np.array([(2.2, 2), (3, 3), (5, 1)])
```
####Output:
```python
array([[2.2, 1. , 0. , 0. , 0. , 0. ],
       [0. , 2.2, 0. , 0. , 0. , 0. ],
       [0. , 0. , 3. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 3. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 3. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 5. ]])
```

In [3]:
X = np.array([(2.2, 2), (3, 3), (5, 1)])

In [4]:
def jordan_matrix(X: np.ndarray) -> np.ndarray:
	ones_1 = np.ones(int(X[0][1]-1))
	m_1 = np.eye(int(X[0][1]))
	m_1 = np.diag(ones_1,1)
	np.fill_diagonal(m_1,X[0][0])

	ones_2 = np.ones(int(X[1][1]-1))
	m_2 = np.eye(int(X[1][1]))
	m_2 = np.diag(ones_2,1)
	np.fill_diagonal(m_2,X[1][0])

	ones_3 = np.ones(int(X[2][1]-1))
	m_3 = np.eye(int(X[2][1]))
	m_3 = np.diag(ones_3,1)
	np.fill_diagonal(m_3,X[2][0])

	diag = [m_1,m_2,m_3]
	a = np.eye(int(X[0][1]+X[1][1]+X[2][1]))

	a[:m_1.shape[0],:m_1.shape[1]] = m_1
	a[m_1.shape[0] : m_1.shape[0] + m_2.shape[0] , m_1.shape[1] : m_1.shape[1] + m_2.shape[1]] = m_2
	a[m_1.shape[0] + m_2.shape[0] : m_1.shape[0] + m_2.shape[0] + m_3.shape[0] ,  m_1.shape[1] + m_2.shape[1]:  m_1.shape[1] + m_2.shape[1] + m_3.shape[1]] = m_3

	return a

In [5]:
jordan_matrix(X)

array([[2.2, 1. , 0. , 0. , 0. , 0. ],
       [0. , 2.2, 0. , 0. , 0. , 0. ],
       [0. , 0. , 3. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 3. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 3. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 5. ]])

# **Сложное выражение** 

На вход подаются целочисленные матрицы AA, BB. Запишите и посчитайте с помощью numpy следующее выражение. Если выполнить операцию корректно нельзя - выведите *None*.
$$
\displaystyle\tan{(A)}\times\ln{(B)}
$$

- × - матричное перемножение.
- Доп. требование: в решении не должно быть конструкции:

```python
try: 
    ...
except:
    ...
```

###**Sample1**
####input:
На вход подается np.ndarray, а не np.matrix. Будьте внимательны!

```python
A = np.array([[3, 4]])
B = np.array([[3, 5],[4, 5]])
```
####Output:
На выход подается двумерный array с размерами (1,2), а не (2,)!

```python
array([[1.44847773, 1.63402166]])
```
###**Sample2**
####input:
На вход подается np.ndarray, а не np.matrix. Будьте внимательны!

```python
A = np.array([[3, 4, 5]])
B = np.array([[-3, 5],[4, -5]])
```
####Output:
```python
None
```

In [6]:
A = np.array([[3, 4]])
B = np.array([[3, 5],[4, 5]])


In [7]:
def complex_expr(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    n = None
    if np.isnan(np.log(B)).any()==True:
        return n
    else:
        return np.dot(np.tan(A),np.log(B))


In [8]:
complex_expr(A,B)

array([[1.44847773, 1.63402166]])

# **Найти ближайший элемент**

Реализуйте функцию, принимающую на вход непустой тензор (может быть многомерным) ***X*** и некоторое число ***a*** и возвращающую ближайший к числу элемент тензора. Если ближайших несколько - выведите минимальный из ближайших. (Вернуть нужно само число, а не индекс числа!)

###Sample
####Input:
```python
X = np.array([[ 1,  2, 13],
              [15,  6,  8],
              [ 7, 18,  9]])
a = 7.2
```
####Output:
```python
7
```


In [9]:
X = np.array([[ 1,  8, 13],
              [8,  6,  8],
              [ 7, 18,  7]])
a = 7.5

In [10]:
import numpy as np

def nearest_value(X: np.ndarray, a: float) -> np.float:
	A = np.abs(X-a)
	idx = np.where(A == A.min())
	two_near = X[idx]
	return two_near.min()

In [11]:
nearest_value(X,a)

7

#**Применение маски**


Даны трехмерный тензор размерности *X(n,k,k)*, состоящий из 0 или 1, или nn картинок *k×k*. Нужно применить к нему указанную маску размерности *(k,k)*: В случае, если биты в маске и картинке совпадают, то результирующий бит должен быть равен 0, иначе 1.
###Sample
####Input:
```python
X = np.array([
              [[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]],
             
              [[ 1, 1, 1],
               [ 1, 1, 1],
               [ 1, 1, 1]]
            ])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])
```
####Output:
```python
array([[[0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]]])
```

In [12]:
X = np.array([
              [[ 1, 0, 1],
               [ 1, 1, 1],
               [ 0, 0, 1]],
             
              [[ 1, 1, 1],
               [ 1, 1, 1],
               [ 1, 1, 1]]
            ])
mask = np.array([[1, 1, 0],
                 [1, 1, 0],
                 [1, 1, 0]])

In [13]:
def tensor_mask(X: np.ndarray, mask: np.ndarray) -> np.ndarray:
    xor = np.logical_xor(X,mask)
    result = np.where(xor==False,0,xor)
    return result
    pass

In [14]:
tensor_mask(X,mask)

array([[[0, 1, 1],
        [0, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]]])

#**Сортировка чисел по маске**

Дан одномерный массив целых чисел. Необходимо отсортировать в нем только числа, которые делятся на 22. При этом начальный массив изменять нельзя.
###Sample
####Input:
```python
A = np.array([43, 66, 34, 55, 78, 105, 2])
```
####Output:
```python
array([ 43,   2,  34,  55,  66, 105,  78])
```

In [15]:
A = np.array([43, 66, 34, 55, 78, 105, 2])

In [16]:
def sort_evens(A: np.ndarray) -> np.ndarray:
    B = A.copy()
    mask = (B%2 == 0)
    B[mask] = np.sort(B[mask])
    return B
    pass

In [17]:
sort_evens(A)

array([ 43,   2,  34,  55,  66, 105,  78])

#**Сумма цифр**

На вход подается np.ndarray c натуральными числами. Надо получить массив сумм цифр в этих числах.

###Sample
####Input:
```python
a = np.array([1241, 354, 121])
```
####Output:
```python
array([ 8, 12, 4])
```

In [22]:
a = np.array([324,213,1231119])

In [23]:
import numpy as np

def num_sum(a: np.ndarray) -> np.ndarray:
	str_to_int = np.vectorize(lambda x: int(x))
	arr_of_digits = np.vectorize(lambda x: str_to_int(list(str(x))), otypes=[object])
	return np.vectorize(lambda x: x.sum())(arr_of_digits(a))

In [24]:
num_sum(a)

array([ 9,  6, 18])

#**NAN**


Одна из важных проблем данных - пустые значения. В numpy и pandas они обычно объявляются специальным типом* np.nan*. В реальных задачах нам часто нужно что-то сделать с этими значениями. Например заменить на 0, среднее или медиану.

Реализуйте функцию, которая во входной вещественной матрице *X* находит все значения *nan* и заменяет их на медиану остальных элементов столбца. Если все элементы столбца матрицы *nan*, то заполняем столбец нулями.
###Sample
####Input:
```python
X = np.array([[np.nan,      4,  np.nan],
              [np.nan, np.nan,       8],
              [np.nan,      5,  np.nan]])
```
####Output:
```python
array([[0. , 4. , 8. ],
       [0. , 4.5, 8. ],
       [0. , 5. , 8. ]])
```

In [25]:
X = np.array([[np.nan,      4, np.nan],
              [np.nan, np.nan, 8],
              [np.nan,      5, np.nan]])

In [26]:
import numpy as np

def replace_nans(X: np.ndarray) -> np.ndarray:
    B = X.copy()
    nan_median = np.nanmedian(B, axis=0)
    nan_median = np.nan_to_num(nan_median)
    B = np.where(np.isnan(B)==True,nan_median,B)
    X = np.where(np.isnan(X)==True,B,X)    
    return X 

In [27]:
replace_nans(X)

/usr/local/lib/python3.6/dist-packages/numpy/lib/nanfunctions.py:1116: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([[0. , 4. , 8. ],
       [0. , 4.5, 8. ],
       [0. , 5. , 8. ]])